# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Maximum Likelihood
tagline:             'Data science blog'
description:         'My personal blog about things connected with data science.'
url:                 http://avsecz.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Žiga Avsec
  email:             avsecz.data@gmail.com
  github:	     avsecz

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/avsecz