# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

# relative_permalinks: true
paginate_path: "page:num"

# Setup
title:               Maximum Likelihood
tagline:             'Data science blog'
description:         'My personal blog about things connected with data science.'
url:                 http://avsecz.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Žiga Avsec
  email:             avsecz.data@gmail.com

# Custom vars
github:
  repo:              https://github.com/avsecz

gems:
   - jekyll-coffeescript
   - jekyll-paginate

